services:
  web:
    build: 
      context: .
      args:
        - BUILD_DEVELOPMENT=development
    restart: always
    command: yarn dev  # uncomment for dev mode
    ports:
      - 3000:3000
    volumes:
      - ./web/src:/web/src
      - ./web/public:/public
    env_file:
      - ./web/.env

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - web
    ports:
      - 8000:80
